# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below.
Vagrant.configure("2") do |config|
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # the centos/6 box is very close to the RHEL that HKBU SciBlade uses.
  config.vm.box = "centos/6"

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  # config.vm.network "forwarded_port", guest: 80, host: 8080

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.

  # share the paco folder:
  config.vm.synced_folder "..", "/vagrant", type: "virtualbox"

  # PROVISIONING
  # run the shell script to install and make FreeFem
  config.vm.provision :shell, path: "installFreeFem.sh"
  # pull the paco repository from github
  # NOTE: no need, as we sync the whole folder to /vagrant
  # config.vm.provision "shell", inline: "git clone https://github.com/fabianlischka/paco.git"
end
